# Pytorch Tensor Basics. 
Credit : Aladdin Persson.

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.__version__)

True
1.9.0+cu111


## Initializing a tensor.

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3], [4,5,6]],
                         dtype=torch.float32,
                         device=device, requires_grad=True)

In [3]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
True


In [4]:
x = torch.empty(size=(3,3)) ## uninitialized random data.
print(x)
x = torch.zeros((3,3))
print(x)
x = torch.ones((3,3))
print(x)
x = torch.rand((3,3)) ## in a uniform distribution (0,1)
print(x)
x = torch.eye(3,3)
print(x)
x = torch.arange(start=1,end=10, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty((3,3)).normal_(mean=0, std=1) ## normal Distribution
print(x)
x = torch.empty((3,3)).uniform_(0, 1) ## uniform Distribution
print(x)
x = torch.diag(torch.ones(3))
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1555, 0.0991, 0.2107],
        [0.1782, 0.7864, 0.4168],
        [0.1827, 0.3295, 0.5258]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[ 0.2639, -0.7730, -0.2116],
        [-0.5817,  0.9920, -0.5601],
        [-0.3100, -0.3765, -0.2387]])
tensor([[0.8105, 0.4682, 0.1930],
        [0.7984, 0.2516, 0.7075],
        [0.4739, 0.4973, 0.0890]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Different Tensor Data Types.

In [5]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool())
print(tensor.short()) ## int16
print(tensor.long()) ## int32
print(tensor.half()) ## float16
print(tensor.float()) ## float32
print(tensor.double()) ## flloat64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


## Tensor Conversion.

In [6]:
import numpy as np 
np_arr = np.array([1,2,3,4,])
print(np_arr)
tensor = torch.from_numpy(np_arr)
print(tensor)
np_arr_2 = tensor.numpy()
print(np_arr_2)

[1 2 3 4]
tensor([1, 2, 3, 4], dtype=torch.int32)
[1 2 3 4]


## Tensor Math.

In [7]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([10,11,12,13,14])
z = x+y
print(z)
z = x-y
print(z)
z = x*y
print(z)
z = y.div(x)
print(z)
z = x.pow(2)
print(z)
z = x ** 2
print(z)

tensor([11, 13, 15, 17, 19])
tensor([-9, -9, -9, -9, -9])
tensor([10, 22, 36, 52, 70])
tensor([10.0000,  5.5000,  4.0000,  3.2500,  2.8000])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])


 ## Comparison.

In [8]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([10,11,12,13,14])
z = x>0
print(z)
z = x<0
print(z)

tensor([True, True, True, True, True])
tensor([False, False, False, False, False])


## Matrix Multiplication.

In [9]:
## Exponentiation.
matrix = torch.rand(5,5)
mat = matrix.matrix_power(5)
print(mat)

## Normal Matmul
x1 = torch.rand((2, 3))
x2 = torch.rand((3, 5))
z = torch.mm(x1, x2)
print(z)
z = x1.mm(x2)
print(z)

## Element Wise Mul.
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([10,11,12,13,14])
z = x * y 
print(z) 

## Dot Product Mul.
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([10,11,12,13,14])
z = torch.dot(x, y)
print(z)

tensor([[ 6.3854,  6.9448,  9.2505,  6.9034,  8.7392],
        [13.2806, 14.4324, 19.2756, 14.4064, 18.1967],
        [ 9.5288, 10.3728, 13.8286, 10.3456, 13.0639],
        [ 9.8140, 10.6507, 14.2326, 10.6426, 13.4557],
        [17.3318, 18.8355, 25.1257, 18.7575, 23.7378]])
tensor([[0.5319, 0.5338, 0.4033, 0.6663, 0.6102],
        [0.3552, 0.5386, 0.2368, 0.3740, 0.4864]])
tensor([[0.5319, 0.5338, 0.4033, 0.6663, 0.6102],
        [0.3552, 0.5386, 0.2368, 0.3740, 0.4864]])
tensor([10, 22, 36, 52, 70])
tensor(190)


In [10]:
## tensor batch Multiplication.
batch = 32 
n = 10
m = 20 
p = 30 
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(tensor1.shape)
print(tensor2.shape)
print(out_bmm.shape)

torch.Size([32, 10, 20])
torch.Size([32, 20, 30])
torch.Size([32, 10, 30])


## Useful Math Operations.

In [11]:
x = torch.arange(0,4)
y = torch.arange(40,44)
print(x)
sum_x = torch.sum(x, dim=0)
print(sum_x)
## min, max op.
max = torch.min(x, dim=0)
min = torch.min(x, dim=0)
argmax = torch.argmax(x, dim=0)
argmin = torch.argmin(x, dim=0)
abs_x = torch.abs(x)
## checking op
z = torch.eq(x,y)
print(z)
## sort
z = torch.sort(y, dim=0, descending=True)
print(z)
## Clamp Op.
z = torch.clamp(x, min=0, max=1)
print(z)

tensor([0, 1, 2, 3])
tensor(6)
tensor([False, False, False, False])
torch.return_types.sort(
values=tensor([43, 42, 41, 40]),
indices=tensor([3, 2, 1, 0]))
tensor([0, 1, 1, 1])


## Tensor Indexing.

In [12]:
## same as pandas dataframe indexing
batch_size = 10
features = 25 
x = torch.rand((batch_size, features))
print(x[0, :].shape)
print(x[:, 0].shape)
print(x[2, 0:10])

x = torch.arange(10)
print(x[8:])

x = torch.rand(3,5)
print(x[0:3, 0:2])

## more advanced
x = torch.arange(10)
print(x[(x<2) & (x>6)])
print(x[x.remainder(2) == 0])

# useful op.
print(torch.where(x>5, x, x*2)) # ternary operation  ? : 
# finding distinct numbers
x = torch.tensor([0,0,1,1,2,2,2,4])
print(x.unique())
## finding num of dim
print(x.ndimension())
# finding num of element
print(x.numel())

torch.Size([25])
torch.Size([10])
tensor([0.8509, 0.6181, 0.6298, 0.8762, 0.8426, 0.6752, 0.0137, 0.0747, 0.9639,
        0.3783])
tensor([8, 9])
tensor([[0.8188, 0.1098],
        [0.4133, 0.5317],
        [0.5476, 0.9962]])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 4])
1
8


## Tensor Reshaping.

In [13]:
x = torch.arange(9)
print(x)
# size reshaping
x_33 = x.reshape(3,3)
print(x_33)
# transpose
print(x_33.t())
## concating tensors
x1 = torch.rand((1,2))
x2 = torch.rand((1,2))
z1 = torch.cat((x1, x2), dim=0)
z2 = torch.cat((x1, x2), dim=1)
print(x1.shape)
print(x2.shape)
print(z1.shape)
print(z2.shape)




tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
torch.Size([1, 2])
torch.Size([1, 2])
torch.Size([2, 2])
torch.Size([1, 4])


## More Advanced Stuff (Most Useful Ones)

In [14]:
## flattening tensors.
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(x.shape)
print(z.shape)

## rotating axis
z = x.permute(0, 2, 1)
print(z.shape)

## add/remove dimensions
x = torch.arange(10)
print(x.shape)
z = x.unsqueeze(0)
print(z.shape)
z = x.unsqueeze(0).unsqueeze(1).unsqueeze(2)
print(z.shape)

z = z.squeeze(2)
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1, 1, 1, 10])
torch.Size([1, 1, 10])
